import type { Pizza, Unidade, Categoria, Configuracoes } from './sanity-queries';

export const fallbackCategorias: Categoria[] = [
  {
    _id: '1',
    nome: 'Clássicas',
    slug: { current: 'classica' },
    descricao: 'As pizzas tradicionais que todo mundo ama',
    ordem: 0,
  },
  {
    _id: '2',
    nome: 'Especiais',
    slug: { current: 'especial' },
    descricao: 'Criações exclusivas do nosso chef',
    ordem: 1,
  },
  {
    _id: '3',
    nome: 'Doces',
    slug: { current: 'doce' },
    descricao: 'Sobremesas irresistíveis',
    ordem: 2,
  },
  {
    _id: '4',
    nome: 'Bebidas',
    slug: { current: 'bebida' },
    descricao: 'Para acompanhar sua pizza',
    ordem: 3,
  },
];

export const fallbackPizzas: Pizza[] = [
  {
    _id: '1',
    nome: 'Margherita',
    slug: { current: 'margherita' },
    descricao:
      'Molho de tomate artesanal, muçarela de búfala, manjericão fresco e azeite extra virgem',
    preco: 49.9,
    categoria: {
      _id: '1',
      nome: 'Clássicas',
      slug: { current: 'classica' },
      descricao: '',
      ordem: 0,
    },
    imagem: { asset: { _ref: '' } },
    ingredientes: ['molho de tomate', 'muçarela de búfala', 'manjericão', 'azeite'],
    destaque: true,
    disponivel: true,
    ordem: 0,
  },
  {
    _id: '2',
    nome: 'Pepperoni',
    slug: { current: 'pepperoni' },
    descricao: 'Muçarela derretida com pepperoni importado e orégano',
    preco: 54.9,
    categoria: {
      _id: '1',
      nome: 'Clássicas',
      slug: { current: 'classica' },
      descricao: '',
      ordem: 0,
    },
    imagem: { asset: { _ref: '' } },
    ingredientes: ['muçarela', 'pepperoni', 'orégano'],
    destaque: true,
    disponivel: true,
    ordem: 1,
  },
  {
    _id: '3',
    nome: 'Trufada',
    slug: { current: 'trufada' },
    descricao: 'Creme de trufas negras, muçarela, parmesão e rúcula',
    preco: 79.9,
    categoria: {
      _id: '2',
      nome: 'Especiais',
      slug: { current: 'especial' },
      descricao: '',
      ordem: 1,
    },
    imagem: { asset: { _ref: '' } },
    ingredientes: ['creme de trufas', 'muçarela', 'parmesão', 'rúcula'],
    destaque: true,
    disponivel: true,
    ordem: 2,
  },
  {
    _id: '4',
    nome: 'Lobster',
    slug: { current: 'lobster' },
    descricao: 'Lagosta grelhada, muçarela, tomate cereja e pesto de manjericão',
    preco: 129.9,
    categoria: {
      _id: '2',
      nome: 'Especiais',
      slug: { current: 'especial' },
      descricao: '',
      ordem: 1,
    },
    imagem: { asset: { _ref: '' } },
    ingredientes: ['lagosta', 'muçarela', 'tomate cereja', 'pesto'],
    destaque: true,
    disponivel: true,
    ordem: 3,
  },
];

export const fallbackUnidades: Unidade[] = [
  {
    _id: '1',
    nome: 'Pizzaria Premium - Centro',
    slug: { current: 'centro' },
    endereco: 'Rua Augusta, 1234 - Consolação, São Paulo - SP',
    cep: '01305-100',
    telefone: '+55-11-3256-1234',
    whatsapp: '5511999990001',
    email: 'centro@pizzariapremium.com.br',
    horarios: {
      segunda: '18:00-23:00',
      terca: '18:00-23:00',
      quarta: '18:00-23:00',
      quinta: '18:00-00:00',
      sexta: '18:00-01:00',
      sabado: '18:00-01:00',
      domingo: '18:00-23:00',
    },
    mapa: { lat: -23.5558, lng: -46.6622 },
    wabiz: 'https://wabiz.com.br/pizzaria-premium-centro',
    instagram: '@pizzariapremiumcentro',
    destaque: true,
    ordem: 0,
  },
  {
    _id: '2',
    nome: 'Pizzaria Premium - Vinhedo',
    slug: { current: 'vinhedo' },
    endereco: 'Rod. Anhanguera, km 100 - Vinhedo - SP',
    cep: '13280-000',
    telefone: '+55-19-3256-5678',
    whatsapp: '5511999990002',
    email: 'vinhedo@pizzariapremium.com.br',
    horarios: {
      segunda: 'Fechado',
      terca: '18:00-23:00',
      quarta: '18:00-23:00',
      quinta: '18:00-23:00',
      sexta: '18:00-00:00',
      sabado: '18:00-00:00',
      domingo: '18:00-23:00',
    },
    mapa: { lat: -23.0187, lng: -46.9713 },
    wabiz: 'https://wabiz.com.br/pizzaria-premium-vinhedo',
    instagram: '@pizzariapremiumvinhedo',
    destaque: false,
    ordem: 1,
  },
  {
    _id: '3',
    nome: 'Pizzaria Premium - Campinas',
    slug: { current: 'campinas' },
    endereco: 'Av. Francisco Glicério, 567 - Centro, Campinas - SP',
    cep: '13013-140',
    telefone: '+55-19-3256-9012',
    whatsapp: '5511999990003',
    email: 'campinas@pizzariapremium.com.br',
    horarios: {
      segunda: '18:00-23:00',
      terca: '18:00-23:00',
      quarta: '18:00-23:00',
      quinta: '18:00-23:00',
      sexta: '18:00-01:00',
      sabado: '18:00-01:00',
      domingo: '18:00-23:00',
    },
    mapa: { lat: -22.9099, lng: -47.0626 },
    wabiz: 'https://wabiz.com.br/pizzaria-premium-campinas',
    instagram: '@pizzariapremiumcampinas',
    destaque: false,
    ordem: 2,
  },
];

export const fallbackConfiguracoes: Configuracoes = {
  _id: 'config',
  nomePizzaria: 'Pizzaria Premium',
  slogan: 'A Melhor Pizza da Cidade',
  descricao: 'Desde 2010, trazendo a melhor pizza da cidade com ingredientes selecionados.',
  telefone: '+55-11-3256-1234',
  whatsapp: '5511999990001',
  email: 'contato@pizzariapremium.com.br',
  instagram: '@pizzariapremium',
  facebook: 'https://facebook.com/pizzariapremium',
  wabiz: 'https://wabiz.com.br/pizzaria-premium',
  googleAnalyticsId: '',
};
