import type { Pizza, Unidade, Categoria, Configuracoes, GaleriaItem } from './sanity-queries';

export const fallbackCategorias: Categoria[] = [
  {
    _id: '1',
    nome: 'Clássicas',
    slug: { current: 'classica' },
    descricao: 'As pizzas tradicionais',
    ordem: 0,
  },
  {
    _id: '2',
    nome: 'Especiais',
    slug: { current: 'especial' },
    descricao: 'Criações exclusivas',
    ordem: 1,
  },
  { _id: '3', nome: 'Doces', slug: { current: 'doce' }, descricao: 'Sobremesas', ordem: 2 },
  {
    _id: '4',
    nome: 'Bebidas',
    slug: { current: 'bebida' },
    descricao: 'Para acompanhar',
    ordem: 3,
  },
];

export const fallbackPizzas: Pizza[] = [
  {
    _id: '1',
    nome: 'Moda da Casa',
    slug: { current: 'moda-da-casa' },
    descricao: 'Nossa assinatura',
    preco: 62.9,
    categoria: {
      _id: '2',
      nome: 'Especiais',
      slug: { current: 'especial' },
      descricao: '',
      ordem: 1,
    },
    imagem: { asset: { _ref: '' } },
    ingredientes: ['muçarela', 'calabresa', 'cebola'],
    destaque: true,
    disponivel: true,
    ordem: 0,
  },
  {
    _id: '2',
    nome: 'Calabresa',
    slug: { current: 'calabresa' },
    descricao: 'Calabresa defumada',
    preco: 54.9,
    categoria: {
      _id: '1',
      nome: 'Clássicas',
      slug: { current: 'classica' },
      descricao: '',
      ordem: 0,
    },
    imagem: { asset: { _ref: '' } },
    ingredientes: ['calabresa', 'cebola'],
    destaque: true,
    disponivel: true,
    ordem: 1,
  },
  {
    _id: '3',
    nome: 'Frango com Catupiry',
    slug: { current: 'frango-catupiry' },
    descricao: 'Frango temperado com catupiry',
    preco: 52.9,
    categoria: {
      _id: '1',
      nome: 'Clássicas',
      slug: { current: 'classica' },
      descricao: '',
      ordem: 0,
    },
    imagem: { asset: { _ref: '' } },
    ingredientes: ['frango', 'catupiry'],
    destaque: true,
    disponivel: true,
    ordem: 2,
  },
];

export const fallbackUnidades: Unidade[] = [
  {
    _id: '1',
    nome: 'Venerato - Campo Limpo',
    slug: { current: 'campo-limpo' },
    endereco: 'Rua Eliane de Araújo Neves, 90, Campo Limpo, São Paulo - SP',
    cep: '',
    telefone: '+55-11-94744-5932',
    whatsapp: '5511947445932',
    email: 'contato@veneratopizzas.com.br',
    horarios: {
      segunda: '18:00-23:00',
      terca: '18:00-23:00',
      quarta: '18:00-23:00',
      quinta: '18:00-23:00',
      sexta: '18:00-01:00',
      sabado: '18:00-01:00',
      domingo: '18:00-23:00',
    },
    mapa: { lat: -23.65, lng: -46.75 },
    wabiz: 'https://veneratopizzas.wabiz.delivery/',
    instagram: '@veneratopizzas',
    destaque: true,
    ordem: 0,
  },
  {
    _id: '2',
    nome: 'Venerato - Taboão Jd. Dracena',
    slug: { current: 'taboao-jd-dracena' },
    endereco: 'Av. Embaixador Assis Chateaubriand, 437, Taboão da Serra - SP',
    cep: '',
    telefone: '+55-11-94744-5932',
    whatsapp: '5511947445932',
    email: 'contato@veneratopizzas.com.br',
    horarios: {
      segunda: '18:00-23:00',
      terca: '18:00-23:00',
      quarta: '18:00-23:00',
      quinta: '18:00-23:00',
      sexta: '18:00-01:00',
      sabado: '18:00-01:00',
      domingo: '18:00-23:00',
    },
    mapa: { lat: -23.55, lng: -46.63 },
    wabiz: 'https://veneratopizzas.wabiz.delivery/',
    instagram: '@veneratopizzas',
    destaque: true,
    ordem: 1,
  },
];

export const fallbackConfiguracoes: Configuracoes = {
  _id: 'config',
  nomePizzaria: 'Venerato Pizzas',
  slogan: 'A melhor pizza da cidade',
  descricao: 'Há mais de 20 anos levando sabor para Taboão da Serra e Campo Limpo.',
  telefone: '+55-11-94744-5932',
  whatsapp: '5511947445932',
  email: 'contato@veneratopizzas.com.br',
  instagram: '@veneratopizzas',
  facebook: 'https://facebook.com/veneratopizzas',
  wabiz: 'https://veneratopizzas.wabiz.delivery/',
  googleAnalyticsId: '',
};

export const fallbackGaleria: GaleriaItem[] = [
  {
    _id: 'galeria-pudim-copo',
    titulo: 'Pudim no Copo',
    descricao: 'Sobremesa cremosa da Venerato para completar o pedido.',
    tipo: 'imagem',
    imagem: '/products/pudim-copo.jpg',
    ordem: 0,
    destaque: true,
  },
  {
    _id: 'galeria-empadas-artesanais',
    titulo: 'Empadas Artesanais',
    descricao: 'Empadas com massa leve e recheio generoso.',
    tipo: 'imagem',
    imagem: '/products/empada.jpg',
    ordem: 1,
    destaque: true,
  },
  {
    _id: 'galeria-pizza-forno',
    titulo: 'Pizza saindo do forno',
    descricao: 'Aquele momento em que a pizza chega no ponto perfeito.',
    tipo: 'imagem',
    imagem: '/pizzas/moda-casa.jpg',
    ordem: 2,
    destaque: false,
  },
  {
    _id: 'galeria-bastidores-venerato',
    titulo: 'Bastidores Venerato',
    descricao: 'Um pouco do movimento real por trás dos pedidos.',
    tipo: 'video',
    video: '/videos/venerato-hero.mp4',
    poster: '/images/hero/hero-1.jpg',
    ordem: 3,
    destaque: false,
  },
];
